--------------------- TAI CHI NHANH 1 (M01)---------------------------
LOGIN : ./ AS SYSDBA
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- USER ADMIN CUA CHI NHANH 1
CREATE USER CN1 IDENTIFIED BY CN1;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO CN1; 

/* CREATE TABLE AND INSERT DATA: 
    BTL1_Branch01.sql */

/* SAU KHI TAO BANG VA INSERT DATA*/

-- TAO CAC USERS
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- USER DIRECTOR
CREATE USER DIRECTOR IDENTIFIED BY DR;
GRANT CONNECT, CREATE DATABASE LINK TO DIRECTOR;

BEGIN
  FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'CN1') LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON CN1.' || t.table_name || ' TO DIRECTOR';
  END LOOP;
END;
/

GRANT INSERT, DELETE, UPDATE ON CN1.EMPLOYEE TO DIRECTOR;

GRANT CREATE PROCEDURE TO DIRECTOR;

-- USER MANAGER
CREATE USER MANAGER_BR1 IDENTIFIED BY MN;
GRANT CONNECT, CREATE DATABASE LINK TO MANAGER_BR1;

GRANT INSERT, DELETE, UPDATE ON CN1.ITEMMANAGE_MANAGER TO MANAGER_BR1;

BEGIN
  FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'CN1') LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON CN1.' || t.table_name || ' TO MANAGER_BR1';
  END LOOP;
END;
/

-- USER STAFF
CREATE USER STAFF_BR1 IDENTIFIED BY ST;
GRANT CONNECT, CREATE DATABASE LINK TO STAFF_BR1;

GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.ITEMMANAGE_STAFF TO STAFF_BR1;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.BILL TO STAFF_BR1;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN1.BILLDETAIL TO STAFF_BR1;

GRANT SELECT ON CN1.CUSTOMER_STAFF TO STAFF_BR1;
GRANT SELECT ON CN1.ITEM TO STAFF_BR1;

--------------------- TAI CHI NHANH 2 (M02)---------------------------
LOGIN : ./ AS SYSDBA
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- USER TAO BANG VA INSERT DU LIEU CUA CHI NHANH 2
CREATE USER CN2 IDENTIFIED BY CN2; 
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO CN2;

/* CREATE TABLE AND INSERT DATA: 
    BTL1_Branch02.sql */

/* SAU KHI TAO BANG VA INSERT DATA*/

-- TAO CAC USERS
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
/* USER DIRECTOR (USER CLONE DE KET NOI DEN DIRECTOR TAI CHI NHANH 1) */
CREATE USER DIRECTOR_BR2 IDENTIFIED BY DR;
GRANT CONNECT, CREATE DATABASE LINK TO DIRECTOR_BR2;

BEGIN
  FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'CN2') LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON CN2.' || t.table_name || ' TO DIRECTOR_BR2';
  END LOOP;
END;
/

GRANT INSERT, DELETE, UPDATE ON CN2.EMPLOYEE TO DIRECTOR_BR2;

-- USER MANAGER
CREATE USER MANAGER_BR2 IDENTIFIED BY MN;
GRANT CONNECT, CREATE DATABASE LINK TO MANAGER_BR2;

GRANT INSERT, DELETE, UPDATE ON CN2.ITEMMANAGE_MANAGER TO MANAGER_BR2;

BEGIN
  FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'CN2') LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON CN2.' || t.table_name || ' TO MANAGER_BR2';
  END LOOP;
END;
/

-- USER STAFF
CREATE USER STAFF_BR2 IDENTIFIED BY ST;
GRANT CONNECT, CREATE DATABASE LINK TO STAFF_BR2;

GRANT SELECT, INSERT, DELETE, UPDATE ON CN2.ITEMMANAGE_STAFF TO STAFF_BR2;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN2.BILL TO STAFF_BR2;
GRANT SELECT, INSERT, DELETE, UPDATE ON CN2.BILLDETAIL TO STAFF_BR2;

GRANT SELECT ON CN2.CUSTOMER_STAFF TO STAFF_BR2;
GRANT SELECT ON CN2.ITEM TO STAFF_BR2;